
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilation.yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 30;
  public static final int TANTQUE = 17;
  public static final int CROFER = 35;
  public static final int MULT = 10;
  public static final int REPETER = 18;
  public static final int SI = 28;
  public static final int LONGEUR = 36;
  public static final int EGALE = 8;
  public static final int VIRGULE = 33;
  public static final int FIN = 4;
  public static final int LIRE = 9;
  public static final int OU = 15;
  public static final int NON = 21;
  public static final int PAROUV = 24;
  public static final int DIV = 11;
  public static final int DIFFERENT = 16;
  public static final int PLUS = 13;
  public static final int DEBUT = 3;
  public static final int EOF = 0;
  public static final int DOUBLEEGALE = 20;
  public static final int error = 1;
  public static final int RETOURNE = 31;
  public static final int MOINS = 12;
  public static final int DEBUT_FONCTION = 32;
  public static final int ET = 14;
  public static final int IDF = 38;
  public static final int SINON = 29;
  public static final int ALORS = 26;
  public static final int PARFER = 25;
  public static final int POINT = 37;
  public static final int CROOUV = 34;
  public static final int CSTENTIERE = 39;
  public static final int SUPERIEUR = 23;
  public static final int PROGRAMME = 2;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 19;
  public static final int ENTIER = 7;
  public static final int INFERIEUR = 22;
  public static final int FINSI = 27;
  public static final int ECRIRE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMME",
  "DEBUT",
  "FIN",
  "POINTVIRGULE",
  "ECRIRE",
  "ENTIER",
  "EGALE",
  "LIRE",
  "MULT",
  "DIV",
  "MOINS",
  "PLUS",
  "ET",
  "OU",
  "DIFFERENT",
  "TANTQUE",
  "REPETER",
  "FINTANTQUE",
  "DOUBLEEGALE",
  "NON",
  "INFERIEUR",
  "SUPERIEUR",
  "PAROUV",
  "PARFER",
  "ALORS",
  "FINSI",
  "SI",
  "SINON",
  "FONCTION",
  "RETOURNE",
  "DEBUT_FONCTION",
  "VIRGULE",
  "CROOUV",
  "CROFER",
  "LONGEUR",
  "POINT",
  "IDF",
  "CSTENTIERE"
  };
}

