
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilation.yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIRE = 6;
  public static final int IDF = 14;
  public static final int EGALE = 8;
  public static final int DEBUT = 3;
  public static final int PROGRAMME = 2;
  public static final int MULT = 10;
  public static final int POINTVIRGULE = 5;
  public static final int FIN = 4;
  public static final int PLUS = 13;
  public static final int EOF = 0;
  public static final int LIRE = 9;
  public static final int ENTIER = 7;
  public static final int DIV = 11;
  public static final int error = 1;
  public static final int CSTENTIERE = 15;
  public static final int MOINS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMME",
  "DEBUT",
  "FIN",
  "POINTVIRGULE",
  "ECRIRE",
  "ENTIER",
  "EGALE",
  "LIRE",
  "MULT",
  "DIV",
  "MOINS",
  "PLUS",
  "IDF",
  "CSTENTIERE"
  };
}

